// src/components/Feeds.svelte
<div class="feeds">
  <h2 v-if="feeds.length !== 0">Posts</h2>
  {#each feeds as feed, i}
    <Feed feed={feed} index={i} />
  {/each}
</div>

<script>
import Feed from './Feed.svelte';
export let feeds: FeedType[]

</script>

<style>
.feeds {
  text-align: left;
  max-width: 800px;
  margin: 0 auto;
  margin-top: 5px;
}
</style>

// src/components/Feeds.vue
<template>
  <div class="feeds">
    <h2 v-if="feeds.length !== 0">Posts</h2>
    <Feed  v-for="(feed, index) in feeds" :key="feed.link" :feed="feed" :index="index"/>
  </div>
</template>

<script>
import Feed from './Feed.vue';

export default {
  name: 'Feeds',
  components: {
    Feed,
  },
  props: {
    feeds: Array,
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.feeds {
  text-align: left;
  max-width: 800px;
  margin: 0 auto;
  margin-top: 5px;
}
</style>
